### ISSUE TITLE
Question: How is this similar/different from Amino?

### ISSUE THREAD

**Issue by DonaldTsang** [Clay-Ferguson/quantizr#10]
To put it simply, Amino is Reddit with extra features. Everyone wants to have a community.
Would it be possible for Quantizr to have similar abilities (like wikis, blogging, DMs, forums, and voting)?
https://www.wikiwand.com/en/Amino_(application)#/Features
- text
- voice chat
- polls
- blog posts
- image posts
- wiki entries
- stories
- quizzes

P.S. The weirder appeal of Amino is its equivalent of "Karma farming".

**Comment by Clay-Ferguson** [comment]
It sounds like Amino has lots of similar features. Quanta (i.e. quantizr project) doesn't do polls, or quizzes, or that kind of stuff yet, but for blogs, text, posting files and images, etc. it has all that. 

Newly added is 'minimum-viable-product' Fediverse support (ActivityPub), so it can function as a social media app, corporate collaboration tool, etc, and also post to and read from Mastodon instances.

**Comment by DonaldTsang** [comment]
I guess we have found "The App That Shall Dominate All Other Community Apps".

**Comment by BrandonKMLee** [comment]
Regarding the design, take a look at https://www.gwern.net/docs/technology/2005-shirky-agroupisitsownworstenemy.pdf
1. handles the user can invest in (the best reputation system is memory)
2. a way for there to be members in good standing, which good works get recognized ("karma system", "name + member since")
3. barriers to participation (named peoples have more ways to display their power)
4. find a way to spare the group from scaling (allow for the divergence and flexibility of community)

If there is an extreme power case of such designs, it is https://graymirror.substack.com/p/the-political-amplifier
1. A powerful app is exclusive. You cannot just decide that you are a member. You have to apply. And once you’re in, you have to keep posting and sharing.
2. A powerful app is disciplined. All your contents are through and for the app. You give way your creativity, and derive consensus, within the app.
3. A powerful app is anonymous. Members should be as safe as possible from meatspace consequences of their in-app life.
4. The app is your main info hub. It stockpiles your library with a complete set of world-building designs and creative ideas.
5. The app is your main social hub. It will organize you into localized friend groups. It also gives you local as well as global news. 
6. The app is an important creative asset. If you need a voice actor, writer, or designer, it is always best to talk to your friends in the app. 
7. Besides chatting, the app can coordinate all kinds of friendly community events. An app can notify you of what to bring and what to do.

In essence, the best platform is one that can allow you to:
- Forkable, mergeable, voting based wikis (Gitless? Version Control? WikiJS?)
- Bipolar-tolerant and divergence-based communities, in better forms than Reddit, 8chan, Telegram, and Discord
- Vote-bomb and Sage tolerant design to prevent subcultural conflicts (Member-only voting? Vouch mechanism? Neo-Karma?)
- Blogs and Galleries that are easily sharable, manageable, and archivable (IPFS? Danbooru?)
